version: '2'
services:
  agent:
    image: lambda3/azure-pipelines-agent:docker
    environment:
      AGENT_PAT:
      AGENT_POOL:
      VS_TENANT:
      DOCKER_USERNAME:
      DOCKER_PASSWORD:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    restart: always
